blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ğŸ¾ğŸ™‹ğŸ¼â€Question
    url: https://github.com/EleanoraResources/support/discussions/
    about: Feel free to ask any questions on our Support Repo Discussions.
